language: ruby
rvm:
  - 2.3.3

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE gbtisaas_test;'

install: "bundle install"

script:
  - rails db:migrate RAILS_ENV=test
  - rails test

deploy:
 provider: heroku
 api-key:
  secure: $HEROKU_API_KEY
 app: gbtisaas
