language: ruby
rvm:
  - 2.3.3

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE gbtisaas_test;'
  - mysql -e 'CREATE USER 'gbtis'@';'
  - mysql -e 'grant all privileges on gbtisaas_test to gbtis@'%';'

install: "bundle install"

script:
  - rails db:migrate RAILS_ENV=test
  - rails test
